#Python Array Programs

In [ ]:
'''
1. It is used to store multiple values in single variable.These values are called as elements and they are of single data type.

2. Basic Operations to be performed on array : 
- Transverse
- Insertion
- Deletion
- Search
- Update

1. Copy an array

In [ ]:
a1=[1,2,3,4]
a2=a1.copy()
print(a2)

[1, 2, 3, 4]


In [ ]:
a1=[1,2,3,4]
a2=[]
for i in range(0,len(a1)):
  a2.append(a1[i])
print(a2)

[1, 2, 3, 4]


In [ ]:
a1=[1,2,3,4]
a2=[]
# for i in range(0,len(a1)):
a2=a1
print(a2)  

[1, 2, 3, 4]


2. Freq of an element in an array.

In [ ]:
a1=[1,2,3,4,3,2,2,2]
for i in range(0,len(a1)-1):
  print(a1[i]," occurs ----> ",a1.count(a1[i]),"times.")

1  occurs ---->  1 times.
2  occurs ---->  4 times.
3  occurs ---->  2 times.
4  occurs ---->  1 times.
3  occurs ---->  2 times.
2  occurs ---->  4 times.
2  occurs ---->  4 times.


In [ ]:
a1=[1,2,3,4,3,2,2,2]
u=list(set(a1))
for i in range(0,len(u)):
  print(a1[i]," occurs ----> ",a1.count(a1[i]),"times.")

1  occurs ---->  1 times.
2  occurs ---->  4 times.
3  occurs ---->  2 times.
4  occurs ---->  1 times.


3. Left Rotation of an array.

In [ ]:
a1=[1,2,3,4]
#no. of left rotation=n
n=3
for i in range(0,n):
  first=a1[0]
  for j in range(0,len(a1)-1):
    a1[j]=a1[j+1]
  a1[len(a1)-1]=first
print(a1)

[4, 1, 2, 3]


4. Duplicate elements of an array.

In [ ]:
a1=[1,2,3,4,3,2]
for i in range(0,len(a1)):
  for j in range(i+1,len(a1)):
    if (a1[i]==a1[j]):
       print(a1[j])

2
3


5. Array in reverse order

In [ ]:
a1=[1,2,3,4,3,2]
a2=a1[::-1]
print(a2)

[2, 3, 4, 3, 2, 1]


In [ ]:
a1=[1,2,3,4,3,2]
for i in range(len(a1)-1, -1, -1):     
    print(a1[i])

2
3
4
3
2
1


6. Elements at even position

In [ ]:
a1=[1,2,3,4,3,2]
for i in range(1,len(a1),2):
  print(a1[i])

2
4
2


7. Elements at odd position

In [ ]:
a1=[1,2,3,4,3,2]
for i in range(0,len(a1),2):
  print(a1[i])

1
3
3


8. Largest no. in array

In [ ]:
a1=[1,2,3,4,3,2]
largest=a1[0]
for i in range(0,len(a1)):
  if a1[i]>largest:
    largest=a1[i]
print("largest= ",largest)

largest=  4


9. Smallest no. in array

In [ ]:
a1=[1,2,3,4,3,2]
smallest=a1[0]
for i in range(0,len(a1)):
  if a1[i]<smallest:
    smallest=a1[i]
print("smallest ",smallest)

smallest  1


10. No. of elements in array.

In [ ]:
a1=[1,2,3,4,3,2]
print(len(a1))

6


In [ ]:
# Unique elements
a1=[1,2,3,4,3,2]
a1=set(a1)
print(len(a1))

4


11. Sum of elements of array.

In [ ]:
a1=[1,2,3,4,3,2]
sum=0
for i in range(0,len(a1)):
  sum+=a1[i]
print(sum)

15


12. Right Rotation of Array.

In [ ]:
arr = [1, 2, 3, 4, 5]
n = 3
     
print("Before ",arr)
     
for i in range(0, n):    
    last = arr[len(arr)-1]
    for j in range(len(arr)-1, -1, -1):    
        arr[j] = arr[j-1]
    arr[0] = last
     
print("After ",arr) 

Before  [1, 2, 3, 4, 5]
After  [3, 4, 5, 1, 2]


13. Array in Ascending Order.

In [ ]:
a1=[1,2,3,4,3,2]
temp=0
for i in range(0,len(a1)):
  for j in range(i+1,len(a1)):
    if a1[i]>a1[j]:
      temp=a1[i]
      a1[i]=a1[j]
      a1[j]=temp
print(a1)

[1, 2, 2, 3, 3, 4]


14. Array in Descending Order.

In [ ]:
a1=[1,2,3,4,3,2]
temp=0
for i in range(0,len(a1)):
  for j in range(i+1,len(a1)):
    if a1[i]<a1[j]:
      temp=a1[i]
      a1[i]=a1[j]
      a1[j]=temp
print(a1)

[4, 3, 3, 2, 2, 1]


# Python Matrix Programs

1. Matrix Addition

In [11]:
a1=[[1,3,8],
    [2,3,5],
    [5,7,7]]
a2=[[2,3,4],
    [2,3,5],
    [1,3,9]]
Result=[[0,0,0],
        [0,0,0],
        [0,0,0]]
print(len(a1)) # gives no. of rows
print(len(a1[0])) # gives no. of columns
for i in range(0,len(a1)):
  for j in range(0,len(a2[0])):
    Result[i][j]=a1[i][j]+a2[i][j]
print(Result)

3
4
[[3, 5, 7], [4, 6, 11], [6, 10, 16]]


2. Matrix Multiplication

In [15]:
a1 = [[5, 4, 3],  
     [2, 4, 6],  
     [4, 7, 9]]    
a2 = [[3, 2, 4],  
     [4, 3, 6],  
     [2, 7, 5]]  
Result=[[0,0,0],
        [0,0,0],
        [0,0,0]]
for i in range(0,len(a1)):
  for j in range(0,len(a2[0])):
    for k in range(0,len(a2)):
      Result[i][j]=Result[i][j]+a1[j][k] * a2[k][j] 
print(Result)

[[37, 58, 103], [37, 58, 103], [37, 58, 103]]


In [16]:
import numpy as np

a1 = [[1, 3, 8],
      [2, 3, 5],
      [5, 7, 7]]

a2 = [[2, 3, 4],
      [2, 3, 5],
      [1, 3, 9]]

result = np.dot(a1, a2)
print(result)

[[ 16  36  91]
 [ 15  30  68]
 [ 31  57 118]]


3. Matrix Transposition

In [17]:
a1 = [[5, 4, 3],  
     [2, 4, 6],  
     [4, 7, 9]]     
Result=[[0,0,0],
        [0,0,0],
        [0,0,0]]
for i in range(0,len(a1)):
  for j in range(0,len(a2[0])):
    Result[i][j]=a1[j][i]
print(Result)       

[[5, 2, 4], [4, 4, 7], [3, 6, 9]]
